In [2]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

In [3]:
load_dotenv()
api_key = os.getenv("WeatherAPI_KEY")

latitude = 32.49 # sialkot
longitude = 74.54 # sialkot
start = 1775001600
end = 1775602800

In [141]:
#base_url_pollution = f"http://api.openweathermap.org/data/2.5/air_pollution?lat={latitude}&lon={longitude}&appid={api_key}"
#base_url_weather = f"https://api.openweathermap.org/data/2.5/weather?lat={latitude}&lon={longitude}&units=metric&appid={api_key}"
base_url_history_pollution = f"http://api.openweathermap.org/data/2.5/air_pollution/history?lat={latitude}&lon={longitude}&start={start}&end={end}&appid={api_key}"

In [142]:
response_pollution = requests.get(url=base_url_history_pollution)

In [143]:
pollution = response_pollution.json()

In [144]:
pollution

{'coord': {'lon': 74.54, 'lat': 32.49},
 'list': [{'main': {'aqi': 4},
   'components': {'co': 1214.09,
    'no': 0.26,
    'no2': 24.55,
    'o3': 4.9,
    'so2': 1.44,
    'pm2_5': 65.62,
    'pm10': 103.18,
    'nh3': 11.48},
   'dt': 1775001600},
  {'main': {'aqi': 4},
   'components': {'co': 1221.59,
    'no': 0.58,
    'no2': 22.94,
    'o3': 3.32,
    'so2': 1.67,
    'pm2_5': 67,
    'pm10': 105.27,
    'nh3': 15.45},
   'dt': 1775005200},
  {'main': {'aqi': 4},
   'components': {'co': 1272.21,
    'no': 2.5,
    'no2': 21.7,
    'o3': 3.92,
    'so2': 2.31,
    'pm2_5': 69.29,
    'pm10': 110.1,
    'nh3': 19.48},
   'dt': 1775008800},
  {'main': {'aqi': 4},
   'components': {'co': 1339.46,
    'no': 6.7,
    'no2': 19.5,
    'o3': 12.07,
    'so2': 3.33,
    'pm2_5': 73.07,
    'pm10': 116.39,
    'nh3': 23.76},
   'dt': 1775012400},
  {'main': {'aqi': 4},
   'components': {'co': 1010.3,
    'no': 1.56,
    'no2': 22.92,
    'o3': 38.87,
    'so2': 9.01,
    'pm2_5': 66.36,
    'pm10': 99.81,
    'nh3': 17.71},
   'dt': 1775016000},
  {'main': {'aqi': 4},
   'components': {'co': 933.73,
    'no': 1.06,
    'no2': 23.08,
    'o3': 44.88,
    'so2': 11.15,
    'pm2_5': 61.12,
    'pm10': 93.91,
    'nh3': 18.24},
   'dt': 1775019600},
  {'main': {'aqi': 4},
   'components': {'co': 931.24,
    'no': 0.78,
    'no2': 23.06,
    'o3': 49.78,
    'so2': 12.06,
    'pm2_5': 58.09,
    'pm10': 92.02,
    'nh3': 20.07},
   'dt': 1775023200},
  {'main': {'aqi': 3},
   'components': {'co': 334,
    'no': 0.09,
    'no2': 7.29,
    'o3': 97.72,
    'so2': 9.87,
    'pm2_5': 26.64,
    'pm10': 50.09,
    'nh3': 6.01},
   'dt': 1775026800},
  {'main': {'aqi': 3},
   'components': {'co': 227.64,
    'no': 0.03,
    'no2': 3.98,
    'o3': 102.53,
    'so2': 6.61,
    'pm2_5': 20.59,
    'pm10': 45.47,
    'nh3': 4.04},
   'dt': 1775030400},
  {'main': {'aqi': 3},
   'components': {'co': 208.91,
    'no': 0.02,
    'no2': 3.44,
    'o3': 101.76,
    'so2': 5.58,
    'pm2_5': 18.56,
    'pm10': 42.92,
    'nh3': 4.07},
   'dt': 1775034000},
  {'main': {'aqi': 2},
   'components': {'co': 207.39,
    'no': 0.03,
    'no2': 3.58,
    'o3': 99.56,
    'so2': 5.42,
    'pm2_5': 17.58,
    'pm10': 41.27,
    'nh3': 5.1},
   'dt': 1775037600},
  {'main': {'aqi': 2},
   'components': {'co': 219.41,
    'no': 0.03,
    'no2': 4.43,
    'o3': 93.67,
    'so2': 5.69,
    'pm2_5': 17.51,
    'pm10': 41.03,
    'nh3': 7.39},
   'dt': 1775041200},
  {'main': {'aqi': 2},
   'components': {'co': 236.18,
    'no': 0.02,
    'no2': 5.61,
    'o3': 88.72,
    'so2': 5.89,
    'pm2_5': 17.54,
    'pm10': 41.17,
    'nh3': 9.79},
   'dt': 1775044800},
  {'main': {'aqi': 2},
   'components': {'co': 345.68,
    'no': 0.01,
    'no2': 11.69,
    'o3': 72.55,
    'so2': 5.91,
    'pm2_5': 19.66,
    'pm10': 46.74,
    'nh3': 17.83},
   'dt': 1775048400},
  {'main': {'aqi': 3},
   'components': {'co': 519.17,
    'no': 0,
    'no2': 19.36,
    'o3': 51.2,
    'so2': 6.01,
    'pm2_5': 24.4,
    'pm10': 58.81,
    'nh3': 28.93},
   'dt': 1775052000},
  {'main': {'aqi': 3},
   'components': {'co': 669.27,
    'no': 0.04,
    'no2': 24.35,
    'o3': 36.81,
    'so2': 6.27,
    'pm2_5': 30.08,
    'pm10': 72.44,
    'nh3': 38.29},
   'dt': 1775055600},
  {'main': {'aqi': 3},
   'components': {'co': 774.4,
    'no': 0.22,
    'no2': 26.78,
    'o3': 26.86,
    'so2': 6.2,
    'pm2_5': 34.94,
    'pm10': 82.81,
    'nh3': 44.34},
   'dt': 1775059200},
  {'main': {'aqi': 3},
   'components': {'co': 886.89,
    'no': 0.55,
    'no2': 29.15,
    'o3': 19.48,
    'so2': 5.85,
    'pm2_5': 40.16,
    'pm10': 92.45,
    'nh3': 45.55},
   'dt': 1775062800},
  {'main': {'aqi': 4},
   'components': {'co': 1022.1,
    'no': 0.73,
    'no2': 33.21,
    'o3': 13.16,
    'so2': 5.35,
    'pm2_5': 45.54,
    'pm10': 100,
    'nh3': 44.67},
   'dt': 1775066400},
  {'main': {'aqi': 3},
   'components': {'co': 1084.11,
    'no': 0.54,
    'no2': 35.31,
    'o3': 10.25,
    'so2': 4.59,
    'pm2_5': 48.05,
    'pm10': 99.15,
    'nh3': 42.03},
   'dt': 1775070000},
  {'main': {'aqi': 3},
   'components': {'co': 1077.93,
    'no': 0.33,
    'no2': 33.85,
    'o3': 10.73,
    'so2': 4.02,
    'pm2_5': 48.92,
    'pm10': 95.03,
    'nh3': 39.9},
   'dt': 1775073600},
  {'main': {'aqi': 3},
   'components': {'co': 1049.41,
    'no': 0.22,
    'no2': 31.16,
    'o3': 12.39,
    'so2': 3.69,
    'pm2_5': 49.55,
    'pm10': 90.98,
    'nh3': 38.02},
   'dt': 1775077200},
  {'main': {'aqi': 3},
   'components': {'co': 994.28,
    'no': 0.21,
    'no2': 27.53,
    'o3': 16.37,
    'so2': 3.51,
    'pm2_5': 49.89,
    'pm10': 86.16,
    'nh3': 35.34},
   'dt': 1775080800},
  {'main': {'aqi': 3},
   'components': {'co': 934.77,
    'no': 0.16,
    'no2': 23.6,
    'o3': 21.15,
    'so2': 3.18,
    'pm2_5': 49.82,
    'pm10': 80.56,
    'nh3': 32.87},
   'dt': 1775084400},
  {'main': {'aqi': 3},
   'components': {'co': 862.39,
    'no': 0.07,
    'no2': 19.74,
    'o3': 27.53,
    'so2': 2.97,
    'pm2_5': 49.38,
    'pm10': 74.94,
    'nh3': 30.44},
   'dt': 1775088000},
  {'main': {'aqi': 3},
   'components': {'co': 721.44,
    'no': 0.01,
    'no2': 14.62,
    'o3': 43.15,
    'so2': 3.43,
    'pm2_5': 46.71,
    'pm10': 66.84,
    'nh3': 24.61},
   'dt': 1775091600},
  {'main': {'aqi': 3},
   'components': {'co': 719.89,
    'no': 0.5,
    'no2': 13.86,
    'o3': 41.58,
    'so2': 3.43,
    'pm2_5': 45.24,
    'pm10': 65.99,
    'nh3': 24.35},
   'dt': 1775095200},
  {'main': {'aqi': 3},
   'components': {'co': 793.37,
    'no': 3.28,
    'no2': 12.95,
    'o3': 40.5,
    'so2': 3.71,
    'pm2_5': 47.31,
    'pm10': 71.62,
    'nh3': 24.86},
   'dt': 1775098800},
  {'main': {'aqi': 4},
   'components': {'co': 889.4,
    'no': 4.25,
    'no2': 15.01,
    'o3': 46.32,
    'so2': 4.48,
    'pm2_5': 51.85,
    'pm10': 80.55,
    'nh3': 26.05},
   'dt': 1775102400},
  {'main': {'aqi': 4},
   'components': {'co': 952.15,
    'no': 2.95,
    'no2': 18.02,
    'o3': 58.24,
    'so2': 5.62,
    'pm2_5': 56.2,
    'pm10': 88.32,
    'nh3': 26.75},
   'dt': 1775106000},
  {'main': {'aqi': 4},
   'components': {'co': 990.66,
    'no': 1.55,
    'no2': 19.6,
    'o3': 75.35,
    'so2': 6.97,
    'pm2_5': 61.92,
    'pm10': 96.13,
    'nh3': 27.64},
   'dt': 1775109600},
  {'main': {'aqi': 3},
   'components': {'co': 353.7,
    'no': 0.17,
    'no2': 5.97,
    'o3': 107.57,
    'so2': 5.79,
    'pm2_5': 26.71,
    'pm10': 46.45,
    'nh3': 9.33},
   'dt': 1775113200},
  {'main': {'aqi': 3},
   'components': {'co': 224.79,
    'no': 0.11,
    'no2': 2.99,
    'o3': 105.43,
    'so2': 3.39,
    'pm2_5': 16.83,
    'pm10': 33.1,
    'nh3': 6.4},
   'dt': 1775116800},
  {'main': {'aqi': 3},
   'components': {'co': 195.72,
    'no': 0.11,
    'no2': 2.39,
    'o3': 104.31,
    'so2': 2.79,
    'pm2_5': 14.95,
    'pm10': 30.54,
    'nh3': 6.1},
   'dt': 1775120400},
  {'main': {'aqi': 3},
   'components': {'co': 193.1,
    'no': 0.11,
    'no2': 2.8,
    'o3': 101.74,
    'so2': 3.1,
    'pm2_5': 14.95,
    'pm10': 30.05,
    'nh3': 7.13},
   'dt': 1775124000},
  {'main': {'aqi': 2},
   'components': {'co': 210.99,
    'no': 0.1,
    'no2': 4.21,
    'o3': 94.82,
    'so2': 3.75,
    'pm2_5': 15.51,
    'pm10': 30.77,
    'nh3': 9.53},
   'dt': 1775127600},
  {'main': {'aqi': 2},
   'components': {'co': 234.52,
    'no': 0.05,
    'no2': 6,
    'o3': 88.09,
    'so2': 4.4,
    'pm2_5': 15.95,
    'pm10': 31.67,
    'nh3': 12.01},
   'dt': 1775131200},
  {'main': {'aqi': 2},
   'components': {'co': 272.47,
    'no': 0.01,
    'no2': 7.98,
    'o3': 79.49,
    'so2': 4.76,
    'pm2_5': 16.98,
    'pm10': 33.89,
    'nh3': 15.49},
   'dt': 1775134800},
  {'main': {'aqi': 2},
   'components': {'co': 320.7,
    'no': 0,
    'no2': 9.34,
    'o3': 71.13,
    'so2': 4.97,
    'pm2_5': 19.08,
    'pm10': 38.54,
    'nh3': 19.35},
   'dt': 1775138400},
  {'main': {'aqi': 2},
   'components': {'co': 362.01,
    'no': 0,
    'no2': 10.16,
    'o3': 66.4,
    'so2': 5.39,
    'pm2_5': 21.38,
    'pm10': 43.42,
    'nh3': 21.97},
   'dt': 1775142000},
  {'main': {'aqi': 2},
   'components': {'co': 404.38,
    'no': 0,
    'no2': 11.42,
    'o3': 61.34,
    'so2': 5.58,
    'pm2_5': 23.11,
    'pm10': 46.82,
    'nh3': 23.68},
   'dt': 1775145600},
  {'main': {'aqi': 3},
   'components': {'co': 468.83,
    'no': 0,
    'no2': 13.96,
    'o3': 56.59,
    'so2': 5.97,
    'pm2_5': 25.34,
    'pm10': 50.77,
    'nh3': 25.14},
   'dt': 1775149200},
  {'main': {'aqi': 3},
   'components': {'co': 552.72,
    'no': 0,
    'no2': 17.57,
    'o3': 50.54,
    'so2': 6.22,
    'pm2_5': 28.33,
    'pm10': 55.36,
    'nh3': 26.68},
   'dt': 1775152800},
  {'main': {'aqi': 3},
   'components': {'co': 611.82,
    'no': 0,
    'no2': 19.77,
    'o3': 47.65,
    'so2': 6.46,
    'pm2_5': 30.97,
    'pm10': 57.84,
    'nh3': 27.07},
   'dt': 1775156400},
  {'main': {'aqi': 3},
   'components': {'co': 628.14,
    'no': 0,
    'no2': 18.97,
    'o3': 45.35,
    'so2': 5.89,
    'pm2_5': 33.56,
    'pm10': 59.22,
    'nh3': 27.23},
   'dt': 1775160000},
  {'main': {'aqi': 3},
   'components': {'co': 617.43,
    'no': 0,
    'no2': 16.72,
    'o3': 44.05,
    'so2': 5.06,
    'pm2_5': 35.82,
    'pm10': 59.48,
    'nh3': 27.1},
   'dt': 1775163600},
  {'main': {'aqi': 3},
   'components': {'co': 579.5,
    'no': 0,
    'no2': 13.91,
    'o3': 45.43,
    'so2': 5.44,
    'pm2_5': 34.51,
    'pm10': 52.12,
    'nh3': 23},
   'dt': 1775167200},
  {'main': {'aqi': 3},
   'components': {'co': 546.97,
    'no': 0,
    'no2': 11.72,
    'o3': 48.34,
    'so2': 5.37,
    'pm2_5': 31.66,
    'pm10': 43.77,
    'nh3': 18.29},
   'dt': 1775170800},
  {'main': {'aqi': 3},
   'components': {'co': 499.51,
    'no': 0,
    'no2': 9.62,
    'o3': 54.08,
    'so2': 4.99,
    'pm2_5': 28.19,
    'pm10': 36.64,
    'nh3': 13.95},
   'dt': 1775174400},
  {'main': {'aqi': 2},
   'components': {'co': 418.55,
    'no': 0,
    'no2': 7.37,
    'o3': 64.21,
    'so2': 4.79,
    'pm2_5': 24.6,
    'pm10': 31.2,
    'nh3': 10.26},
   'dt': 1775178000},
  {'main': {'aqi': 2},
   'components': {'co': 378.26,
    'no': 0,
    'no2': 6.73,
    'o3': 70.11,
    'so2': 5.4,
    'pm2_5': 23.56,
    'pm10': 30.83,
    'nh3': 9.68},
   'dt': 1775181600},
  {'main': {'aqi': 2},
   'components': {'co': 395.41,
    'no': 0.02,
    'no2': 7.83,
    'o3': 66.11,
    'so2': 5.75,
    'pm2_5': 24.43,
    'pm10': 33.13,
    'nh3': 10.55},
   'dt': 1775185200},
  {'main': {'aqi': 3},
   'components': {'co': 433.23,
    'no': 0.27,
    'no2': 8.65,
    'o3': 61.52,
    'so2': 5.84,
    'pm2_5': 25.63,
    'pm10': 33.6,
    'nh3': 9.91},
   'dt': 1775188800},
  {'main': {'aqi': 3},
   'components': {'co': 458.05,
    'no': 0.53,
    'no2': 8.02,
    'o3': 60.64,
    'so2': 4.88,
    'pm2_5': 26.31,
    'pm10': 33.05,
    'nh3': 8.78},
   'dt': 1775192400},
  {'main': {'aqi': 3},
   'components': {'co': 469.29,
    'no': 0.69,
    'no2': 6.7,
    'o3': 65.54,
    'so2': 4.16,
    'pm2_5': 27.53,
    'pm10': 33.63,
    'nh3': 8.22},
   'dt': 1775196000},
  {'main': {'aqi': 3},
   'components': {'co': 423.74,
    'no': 0.34,
    'no2': 5.12,
    'o3': 71.49,
    'so2': 3.23,
    'pm2_5': 25.17,
    'pm10': 30.01,
    'nh3': 6.82},
   'dt': 1775199600},
  {'main': {'aqi': 2},
   'components': {'co': 369.75,
    'no': 0.3,
    'no2': 4.21,
    'o3': 73.65,
    'so2': 2.99,
    'pm2_5': 20.95,
    'pm10': 25.1,
    'nh3': 6.74},
   'dt': 1775203200},
  {'main': {'aqi': 2},
   'components': {'co': 319.41,
    'no': 0.26,
    'no2': 3.71,
    'o3': 77.19,
    'so2': 3.24,
    'pm2_5': 17.61,
    'pm10': 21.42,
    'nh3': 6.53},
   'dt': 1775206800},
  {'main': {'aqi': 2},
   'components': {'co': 267.89,
    'no': 0.17,
    'no2': 3.25,
    'o3': 80.04,
    'so2': 3.67,
    'pm2_5': 13.73,
    'pm10': 16.97,
    'nh3': 5.51},
   'dt': 1775210400},
  {'main': {'aqi': 2},
   'components': {'co': 237.77,
    'no': 0.11,
    'no2': 3.23,
    'o3': 77.72,
    'so2': 3.54,
    'pm2_5': 10.98,
    'pm10': 14.19,
    'nh3': 5.68},
   'dt': 1775214000},
  {'main': {'aqi': 2},
   'components': {'co': 224.33,
    'no': 0.06,
    'no2': 3.66,
    'o3': 76.66,
    'so2': 3.58,
    'pm2_5': 9.54,
    'pm10': 13.02,
    'nh3': 6.3},
   'dt': 1775217600},
  {'main': {'aqi': 2},
   'components': {'co': 237.72,
    'no': 0.02,
    'no2': 5.24,
    'o3': 73.24,
    'so2': 3.48,
    'pm2_5': 9.5,
    'pm10': 14.22,
    'nh3': 8.56},
   'dt': 1775221200},
  {'main': {'aqi': 2},
   'components': {'co': 278.73,
    'no': 0,
    'no2': 7.48,
    'o3': 67.44,
    'so2': 3.65,
    'pm2_5': 10.94,
    'pm10': 18.03,
    'nh3': 11.84},
   'dt': 1775224800},
  {'main': {'aqi': 2},
   'components': {'co': 316.88,
    'no': 0,
    'no2': 9.1,
    'o3': 62.27,
    'so2': 3.85,
    'pm2_5': 12.73,
    'pm10': 22.1,
    'nh3': 14.02},
   'dt': 1775228400},
  {'main': {'aqi': 2},
   'components': {'co': 352.62,
    'no': 0,
    'no2': 10.3,
    'o3': 55.6,
    'so2': 3.7,
    'pm2_5': 14.87,
    'pm10': 26.72,
    'nh3': 14.77},
   'dt': 1775232000},
  {'main': {'aqi': 2},
   'components': {'co': 394.32,
    'no': 0,
    'no2': 11.42,
    'o3': 48.63,
    'so2': 3.47,
    'pm2_5': 17.74,
    'pm10': 32.77,
    'nh3': 14.59},
   'dt': 1775235600},
  {'main': {'aqi': 2},
   'components': {'co': 425.62,
    'no': 0,
    'no2': 12.17,
    'o3': 42.84,
    'so2': 3.19,
    'pm2_5': 20.17,
    'pm10': 36.93,
    'nh3': 13.63},
   'dt': 1775239200},
  {'main': {'aqi': 2},
   'components': {'co': 431.4,
    'no': 0,
    'no2': 12.06,
    'o3': 37.42,
    'so2': 2.71,
    'pm2_5': 21.35,
    'pm10': 37.43,
    'nh3': 12.8},
   'dt': 1775242800},
  {'main': {'aqi': 2},
   'components': {'co': 427.12,
    'no': 0,
    'no2': 11.24,
    'o3': 32.66,
    'so2': 2.18,
    'pm2_5': 22.41,
    'pm10': 37.07,
    'nh3': 11.31},
   'dt': 1775246400},
  {'main': {'aqi': 2},
   'components': {'co': 421.05,
    'no': 0,
    'no2': 10.23,
    'o3': 28.72,
    'so2': 1.79,
    'pm2_5': 23.99,
    'pm10': 37.32,
    'nh3': 10.23},
   'dt': 1775250000},
  {'main': {'aqi': 3},
   'components': {'co': 416.84,
    'no': 0,
    'no2': 9.39,
    'o3': 24.9,
    'so2': 1.52,
    'pm2_5': 25.74,
    'pm10': 38.03,
    'nh3': 9.37},
   'dt': 1775253600},
  {'main': {'aqi': 3},
   'components': {'co': 416.28,
    'no': 0,
    'no2': 8.89,
    'o3': 21.9,
    'so2': 1.38,
    'pm2_5': 27.48,
    'pm10': 38.92,
    'nh3': 8.74},
   'dt': 1775257200},
  {'main': {'aqi': 3},
   'components': {'co': 414.3,
    'no': 0.01,
    'no2': 8.64,
    'o3': 20.25,
    'so2': 1.4,
    'pm2_5': 29.23,
    'pm10': 39.72,
    'nh3': 8.42},
   'dt': 1775260800},
  {'main': {'aqi': 3},
   'components': {'co': 414.95,
    'no': 0.01,
    'no2': 8.78,
    'o3': 19.61,
    'so2': 1.62,
    'pm2_5': 30.54,
    'pm10': 40.15,
    'nh3': 8.36},
   'dt': 1775264400},
  {'main': {'aqi': 3},
   'components': {'co': 441.53,
    'no': 0.41,
    'no2': 9.24,
    'o3': 17.93,
    'so2': 1.89,
    'pm2_5': 31.5,
    'pm10': 42.71,
    'nh3': 9.27},
   'dt': 1775268000},
  {'main': {'aqi': 3},
   'components': {'co': 472.46,
    'no': 2.04,
    'no2': 8.53,
    'o3': 21.52,
    'so2': 2.39,
    'pm2_5': 32.29,
    'pm10': 45.07,
    'nh3': 11.29},
   'dt': 1775271600},
  {'main': {'aqi': 3},
   'components': {'co': 463.94,
    'no': 2.45,
    'no2': 7.91,
    'o3': 32.89,
    'so2': 2.99,
    'pm2_5': 31.79,
    'pm10': 44.59,
    'nh3': 13.4},
   'dt': 1775275200},
  {'main': {'aqi': 3},
   'components': {'co': 451.04,
    'no': 2.02,
    'no2': 7.27,
    'o3': 47.06,
    'so2': 3.11,
    'pm2_5': 31.57,
    'pm10': 44.92,
    'nh3': 15.26},
   'dt': 1775278800},
  {'main': {'aqi': 3},
   'components': {'co': 424.38,
    'no': 1.39,
    'no2': 6,
    'o3': 66.28,
    'so2': 3.29,
    'pm2_5': 33.96,
    'pm10': 47.32,
    'nh3': 16},
   'dt': 1775282400},
  {'main': {'aqi': 2},
   'components': {'co': 206.66,
    'no': 0.38,
    'no2': 2.14,
    'o3': 90.35,
    'so2': 5.04,
    'pm2_5': 15.58,
    'pm10': 24.11,
    'nh3': 4.98},
   'dt': 1775286000},
  {'main': {'aqi': 3},
   'components': {'co': 170.16,
    'no': 0.21,
    'no2': 1.3,
    'o3': 101.11,
    'so2': 3.77,
    'pm2_5': 10.05,
    'pm10': 16.05,
    'nh3': 3.17},
   'dt': 1775289600},
  {'main': {'aqi': 3},
   'components': {'co': 175.81,
    'no': 0.21,
    'no2': 1.38,
    'o3': 108.15,
    'so2': 3.84,
    'pm2_5': 10.37,
    'pm10': 15.84,
    'nh3': 3.28},
   'dt': 1775293200},
  {'main': {'aqi': 3},
   'components': {'co': 201.19,
    'no': 0.24,
    'no2': 1.99,
    'o3': 112.65,
    'so2': 4.92,
    'pm2_5': 13.47,
    'pm10': 18.95,
    'nh3': 4.1},
   'dt': 1775296800},
  {'main': {'aqi': 3},
   'components': {'co': 242.31,
    'no': 0.25,
    'no2': 3.3,
    'o3': 112.48,
    'so2': 6.55,
    'pm2_5': 18.29,
    'pm10': 23.84,
    'nh3': 5.59},
   'dt': 1775300400},
  {'main': {'aqi': 3},
   'components': {'co': 282.96,
    'no': 0.17,
    'no2': 5.19,
    'o3': 107.81,
    'so2': 7.77,
    'pm2_5': 21.92,
    'pm10': 26.99,
    'nh3': 6.61},
   'dt': 1775304000},
  {'main': {'aqi': 3},
   'components': {'co': 378.82,
    'no': 0.09,
    'no2': 10.13,
    'o3': 84.4,
    'so2': 6.38,
    'pm2_5': 26.34,
    'pm10': 33.42,
    'nh3': 11.89},
   'dt': 1775307600},
  {'main': {'aqi': 3},
   'components': {'co': 518.44,
    'no': 0,
    'no2': 15.67,
    'o3': 59.83,
    'so2': 4.78,
    'pm2_5': 32.6,
    'pm10': 44.89,
    'nh3': 17.86},
   'dt': 1775311200},
  {'main': {'aqi': 3},
   'components': {'co': 631.89,
    'no': 0,
    'no2': 19.05,
    'o3': 46.09,
    'so2': 4.04,
    'pm2_5': 38.62,
    'pm10': 56.56,
    'nh3': 19.66},
   'dt': 1775314800},
  {'main': {'aqi': 3},
   'components': {'co': 710.7,
    'no': 0.01,
    'no2': 20.79,
    'o3': 38.28,
    'so2': 3.63,
    'pm2_5': 44.05,
    'pm10': 66.73,
    'nh3': 19.06},
   'dt': 1775318400},
  {'main': {'aqi': 3},
   'components': {'co': 769.53,
    'no': 0.02,
    'no2': 21.53,
    'o3': 33.45,
    'so2': 3.29,
    'pm2_5': 49.52,
    'pm10': 74.99,
    'nh3': 16.13},
   'dt': 1775322000},
  {'main': {'aqi': 4},
   'components': {'co': 801.03,
    'no': 0.01,
    'no2': 21.72,
    'o3': 29.59,
    'so2': 2.91,
    'pm2_5': 53.52,
    'pm10': 79.32,
    'nh3': 13.48},
   'dt': 1775325600},
  {'main': {'aqi': 4},
   'components': {'co': 790.66,
    'no': 0.01,
    'no2': 20.61,
    'o3': 25.76,
    'so2': 2.35,
    'pm2_5': 54,
    'pm10': 77.69,
    'nh3': 11.1},
   'dt': 1775329200},
  {'main': {'aqi': 4},
   'components': {'co': 802.8,
    'no': 0.01,
    'no2': 19.55,
    'o3': 20.15,
    'so2': 1.76,
    'pm2_5': 54.63,
    'pm10': 77.22,
    'nh3': 9.68},
   'dt': 1775332800},
  {'main': {'aqi': 4},
   'components': {'co': 804.31,
    'no': 0.02,
    'no2': 18.02,
    'o3': 16.39,
    'so2': 1.51,
    'pm2_5': 54.66,
    'pm10': 76.28,
    'nh3': 9.52},
   'dt': 1775336400},
  {'main': {'aqi': 4},
   'components': {'co': 792.64,
    'no': 0.04,
    'no2': 16.5,
    'o3': 14.02,
    'so2': 1.43,
    'pm2_5': 53.17,
    'pm10': 73.58,
    'nh3': 9.56},
   'dt': 1775340000},
  {'main': {'aqi': 4},
   'components': {'co': 782.73,
    'no': 0.05,
    'no2': 15.06,
    'o3': 11.71,
    'so2': 1.22,
    'pm2_5': 50.96,
    'pm10': 69.08,
    'nh3': 8.79},
   'dt': 1775343600},
  {'main': {'aqi': 3},
   'components': {'co': 764.94,
    'no': 0.05,
    'no2': 13.71,
    'o3': 10.42,
    'so2': 1.15,
    'pm2_5': 48.49,
    'pm10': 63.67,
    'nh3': 8.2},
   'dt': 1775347200},
  {'main': {'aqi': 3},
   'components': {'co': 730.32,
    'no': 0.05,
    'no2': 12.59,
    'o3': 10.18,
    'so2': 1.29,
    'pm2_5': 44.55,
    'pm10': 57.87,
    'nh3': 7.73},
   'dt': 1775350800},
  {'main': {'aqi': 3},
   'components': {'co': 720.37,
    'no': 1.13,
    'no2': 10.95,
    'o3': 11.21,
    'so2': 1.61,
    'pm2_5': 40.88,
    'pm10': 55.33,
    'nh3': 8.36},
   'dt': 1775354400},
  {'main': {'aqi': 3},
   'components': {'co': 717.55,
    'no': 3.93,

In [145]:
length = len(pollution['list'])
length

144

In [146]:
pollution = pollution['list']

In [147]:
sample = {}

In [148]:
sample["aqi"] = pollution[5]['main']
sample["aqi"]=sample["aqi"]["aqi"]
sample

{'aqi': 4}

In [149]:
sample["dt"] = pollution[5]['dt']
sample

{'aqi': 4, 'dt': 1775019600}

In [150]:
sample = {}
temp = []

In [151]:
for hourly_data in pollution:
    sample = {}
    sample["aqi"] = hourly_data['main']["aqi"]
    sample['co'] = hourly_data['components']['co']
    sample['no2'] = hourly_data['components']['no2']
    sample['o3'] = hourly_data['components']['o3']
    sample['so2'] = hourly_data['components']['so2']
    sample['pm2_5'] = hourly_data['components']['pm2_5']
    sample['pm10'] = hourly_data['components']['pm10']
    sample['nh3'] = hourly_data['components']['nh3']
    sample["dt"] = hourly_data['dt']
    temp.append(sample)

In [152]:
data = pd.DataFrame(temp)
data.head()

   aqi       co    no2     o3   so2  pm2_5    pm10    nh3          dt
0    4  1214.09  24.55   4.90  1.44  65.62  103.18  11.48  1775001600
1    4  1221.59  22.94   3.32  1.67  67.00  105.27  15.45  1775005200
2    4  1272.21  21.70   3.92  2.31  69.29  110.10  19.48  1775008800
3    4  1339.46  19.50  12.07  3.33  73.07  116.39  23.76  1775012400
4    4  1010.30  22.92  38.87  9.01  66.36   99.81  17.71  1775016000

In [153]:
data['datetime'] = pd.to_datetime(data['dt'], unit='s')
data.head()

,aqi,co,no2,o3,so2,pm2_5,pm10,nh3,dt,datetime
0,4,1214.09,24.55,4.90,1.44,65.62,103.18,11.48,1775001600,2026-04-01 00:00:00
1,4,1221.59,22.94,3.32,1.67,67.00,105.27,15.45,1775005200,2026-04-01 01:00:00
2,4,1272.21,21.70,3.92,2.31,69.29,110.10,19.48,1775008800,2026-04-01 02:00:00
3,4,1339.46,19.50,12.07,3.33,73.07,116.39,23.76,1775012400,2026-04-01 03:00:00
4,4,1010.30,22.92,38.87,9.01,66.36,99.81,17.71,1775016000,2026-04-01 04:00:00

In [154]:
data['date'] = data['datetime'].dt.date
data['hour'] = data['datetime'].dt.hour
data = data.drop(['dt'],axis=1)

In [155]:
data.head()

,aqi,co,no2,o3,so2,pm2_5,pm10,nh3,datetime,date,hour
0,4,1214.09,24.55,4.90,1.44,65.62,103.18,11.48,2026-04-01 00:00:00,2026-04-01,0
1,4,1221.59,22.94,3.32,1.67,67.00,105.27,15.45,2026-04-01 01:00:00,2026-04-01,1
2,4,1272.21,21.70,3.92,2.31,69.29,110.10,19.48,2026-04-01 02:00:00,2026-04-01,2
3,4,1339.46,19.50,12.07,3.33,73.07,116.39,23.76,2026-04-01 03:00:00,2026-04-01,3
4,4,1010.30,22.92,38.87,9.01,66.36,99.81,17.71,2026-04-01 04:00:00,2026-04-01,4

In [9]:
# History Weather

In [112]:
base_url_history_weather = "https://archive-api.open-meteo.com/v1/archive?latitude=32.49&longitude=74.54&start_date=2026-04-01&end_date=2026-04-07&hourly=wind_speed_100m,precipitation,apparent_temperature,wind_gusts_10m,vapour_pressure_deficit,relative_humidity_2m&timezone=auto"

In [113]:
response_weather = requests.get(url=base_url_history_weather)

In [114]:
weather = response_weather.json()

In [115]:
weather.keys()

dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

In [116]:
weather

{'latitude': 32.51318,
 'longitude': 74.56204,
 'generationtime_ms': 11.891365051269531,
 'utc_offset_seconds': 18000,
 'timezone': 'Asia/Karachi',
 'timezone_abbreviation': 'GMT+5',
 'elevation': 267.0,
 'hourly_units': {'time': 'iso8601',
  'wind_speed_100m': 'km/h',
  'precipitation': 'mm',
  'apparent_temperature': '°C',
  'wind_gusts_10m': 'km/h',
  'vapour_pressure_deficit': 'kPa',
  'relative_humidity_2m': '%'},
 'hourly': {'time': ['2026-04-01T00:00',
   '2026-04-01T01:00',
   '2026-04-01T02:00',
   '2026-04-01T03:00',
   '2026-04-01T04:00',
   '2026-04-01T05:00',
   '2026-04-01T06:00',
   '2026-04-01T07:00',
   '2026-04-01T08:00',
   '2026-04-01T09:00',
   '2026-04-01T10:00',
   '2026-04-01T11:00',
   '2026-04-01T12:00',
   '2026-04-01T13:00',
   '2026-04-01T14:00',
   '2026-04-01T15:00',
   '2026-04-01T16:00',
   '2026-04-01T17:00',
   '2026-04-01T18:00',
   '2026-04-01T19:00',
   '2026-04-01T20:00',
   '2026-04-01T21:00',
   '2026-04-01T22:00',
   '2026-04-01T23:00',
   '2026-04-02T00:00',
   '2026-04-02T01:00',
   '2026-04-02T02:00',
   '2026-04-02T03:00',
   '2026-04-02T04:00',
   '2026-04-02T05:00',
   '2026-04-02T06:00',
   '2026-04-02T07:00',
   '2026-04-02T08:00',
   '2026-04-02T09:00',
   '2026-04-02T10:00',
   '2026-04-02T11:00',
   '2026-04-02T12:00',
   '2026-04-02T13:00',
   '2026-04-02T14:00',
   '2026-04-02T15:00',
   '2026-04-02T16:00',
   '2026-04-02T17:00',
   '2026-04-02T18:00',
   '2026-04-02T19:00',
   '2026-04-02T20:00',
   '2026-04-02T21:00',
   '2026-04-02T22:00',
   '2026-04-02T23:00',
   '2026-04-03T00:00',
   '2026-04-03T01:00',
   '2026-04-03T02:00',
   '2026-04-03T03:00',
   '2026-04-03T04:00',
   '2026-04-03T05:00',
   '2026-04-03T06:00',
   '2026-04-03T07:00',
   '2026-04-03T08:00',
   '2026-04-03T09:00',
   '2026-04-03T10:00',
   '2026-04-03T11:00',
   '2026-04-03T12:00',
   '2026-04-03T13:00',
   '2026-04-03T14:00',
   '2026-04-03T15:00',
   '2026-04-03T16:00',
   '2026-04-03T17:00',
   '2026-04-03T18:00',
   '2026-04-03T19:00',
   '2026-04-03T20:00',
   '2026-04-03T21:00',
   '2026-04-03T22:00',
   '2026-04-03T23:00',
   '2026-04-04T00:00',
   '2026-04-04T01:00',
   '2026-04-04T02:00',
   '2026-04-04T03:00',
   '2026-04-04T04:00',
   '2026-04-04T05:00',
   '2026-04-04T06:00',
   '2026-04-04T07:00',
   '2026-04-04T08:00',
   '2026-04-04T09:00',
   '2026-04-04T10:00',
   '2026-04-04T11:00',
   '2026-04-04T12:00',
   '2026-04-04T13:00',
   '2026-04-04T14:00',
   '2026-04-04T15:00',
   '2026-04-04T16:00',
   '2026-04-04T17:00',
   '2026-04-04T18:00',
   '2026-04-04T19:00',
   '2026-04-04T20:00',
   '2026-04-04T21:00',
   '2026-04-04T22:00',
   '2026-04-04T23:00',
   '2026-04-05T00:00',
   '2026-04-05T01:00',
   '2026-04-05T02:00',
   '2026-04-05T03:00',
   '2026-04-05T04:00',
   '2026-04-05T05:00',
   '2026-04-05T06:00',
   '2026-04-05T07:00',
   '2026-04-05T08:00',
   '2026-04-05T09:00',
   '2026-04-05T10:00',
   '2026-04-05T11:00',
   '2026-04-05T12:00',
   '2026-04-05T13:00',
   '2026-04-05T14:00',
   '2026-04-05T15:00',
   '2026-04-05T16:00',
   '2026-04-05T17:00',
   '2026-04-05T18:00',
   '2026-04-05T19:00',
   '2026-04-05T20:00',
   '2026-04-05T21:00',
   '2026-04-05T22:00',
   '2026-04-05T23:00',
   '2026-04-06T00:00',
   '2026-04-06T01:00',
   '2026-04-06T02:00',
   '2026-04-06T03:00',
   '2026-04-06T04:00',
   '2026-04-06T05:00',
   '2026-04-06T06:00',
   '2026-04-06T07:00',
   '2026-04-06T08:00',
   '2026-04-06T09:00',
   '2026-04-06T10:00',
   '2026-04-06T11:00',
   '2026-04-06T12:00',
   '2026-04-06T13:00',
   '2026-04-06T14:00',
   '2026-04-06T15:00',
   '2026-04-06T16:00',
   '2026-04-06T17:00',
   '2026-04-06T18:00',
   '2026-04-06T19:00',
   '2026-04-06T20:00',
   '2026-04-06T21:00',
   '2026-04-06T22:00',
   '2026-04-06T23:00',
   '2026-04-07T00:00',
   '2026-04-07T01:00',
   '2026-04-07T02:00',
   '2026-04-07T03:00',
   '2026-04-07T04:00',
   '2026-04-07T05:00',
   '2026-04-07T06:00',
   '2026-04-07T07:00',
   '2026-04-07T08:00',
   '2026-04-07T09:00',
   '2026-04-07T10:00',
   '2026-04-07T11:00',
   '2026-04-07T12:00',
   '2026-04-07T13:00',
   '2026-04-07T14:00',
   '2026-04-07T15:00',
   '2026-04-07T16:00',
   '2026-04-07T17:00',
   '2026-04-07T18:00',
   '2026-04-07T19:00',
   '2026-04-07T20:00',
   '2026-04-07T21:00',
   '2026-04-07T22:00',
   '2026-04-07T23:00'],
  'wind_speed_100m': [28.3,
   24.0,
   15.5,
   20.3,
   16.4,
   4.4,
   4.8,
   9.2,
   13.8,
   5.9,
   5.4,
   4.3,
   4.9,
   6.0,
   4.9,
   4.4,
   3.6,
   12.4,
   13.5,
   10.4,
   8.6,
   7.9,
   10.6,
   1.1,
   3.0,
   11.7,
   13.7,
   15.3,
   15.8,
   15.6,
   15.3,
   10.8,
   10.2,
   3.2,
   4.6,
   1.5,
   3.7,
   5.0,
   5.9,
   9.6,
   14.6,
   4.7,
   2.0,
   3.1,
   3.6,
   13.3,
   20.7,
   21.6,
   21.1,
   19.8,
   27.2,
   15.1,
   20.8,
   5.8,
   12.8,
   20.7,
   7.0,
   21.6,
   6.1,
   18.1,
   14.4,
   25.9,
   17.8,
   23.7,
   22.9,
   14.8,
   16.7,
   27.8,
   28.1,
   37.5,
   39.6,
   27.2,
   17.8,
   18.2,
   13.6,
   21.4,
   18.1,
   23.4,
   21.9,
   16.4,
   22.0,
   13.1,
   18.2,
   20.4,
   6.5,
   4.4,
   15.9,
   10.2,
   6.7,
   19.4,
   5.1,
   15.5,
   23.8,
   22.5,
   16.9,
   17.3,
   12.9,
   9.3,
   8.8,
   13.3,
   16.6,
   15.1,
   10.7,
   7.8,
   7.1,
   2.4,
   0.7,
   0.3,
   4.6,
   4.2,
   6.4,
   7.0,
   6.6,
   11.0,
   14.3,
   12.2,
   8.8,
   7.6,
   10.8,
   16.6,
   9.4,
   5.2,
   9.0,
   11.9,
   13.4,
   15.9,
   12.7,
   10.4,
   7.2,
   2.8,
   2.1,
   6.9,
   6.0,
   7.2,
   9.4,
   9.7,
   11.5,
   5.9,
   8.2,
   3.2,
   2.4,
   5.8,
   11.1,
   12.4,
   20.3,
   20.9,
   10.5,
   9.9,
   5.6,
   19.0,
   15.6,
   22.7,
   19.7,
   14.4,
   10.3,
   14.0,
   16.7,
   17.9,
   18.4,
   24.4,
   26.2,
   27.7,
   25.0,
   21.2,
   18.6,
   21.3,
   16.7,
   28.0],
  'precipitation': [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.5,
   0.0,
   0.0,
   0.3,
   1.9,
   0.3,
   1.4,
   0.2,
   0.3,
   0.0,
   0.0,
   0.1,
   0.0,
   1.4,
   0.2,
   0.1,
   0.5,
   4.8,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   2.7,
   0.5,
   0.0,
   5.9,
   3.1,
   0.0,
   0.0,
   0.0,
   1.6,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.3,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   1.1,
   1.4,
   2.0,
   0.6,
   1.1,
   3.7,
   3.7,
   3.2,
   2.2,
   0.7,
   0.2,
   0.1],
  'apparent_temperature': [19.2,
   20.6,
   19.1,
   18.4,
   17.9,
   19.7,
   18.3,
   18.9,
   21.6,
   24.2,
   25.8,
   27.4,
   29.2,
   29.7,
   29.9,
   28.7,
   27.8,
   26.7,
   25.3,
   23.5,
   23.1,
   22.3,
   20.4,
   21.4,
   21.0,
   20.3,
   20.2,
   19.8,
   19.6,
   19.2,
   19.1,
   20.3,
   23.1,
   26.8,
   27.3,
   31.5,
   32.8,
   32.3,
   32.0,
   30.3,
   28.6,
   32.5,
   29.6,
   26.6,
   25.7,
   23.3,
   21.9,
   22.5,
   23.0,
   22.8,
   23.3,
   23.1,
   20.4,
   22.7,
   21.9,
   20.9,
   23.4,
   23.7,
   25.4,
   21.0,
   21.9,
   21.0,
   21.8,
   21.8,
   21.8,
   22.8,
   22.0,
   19.7,
   18.5,
   17.0,
   16.2,
   16.8,
   17.0,
   15.9,
   15.6,
   14.3,
   14.0,
   14.6,
   15.2,
   17.0,
   20.6,
   23.1,
   21.7,
   20.6,
   24.5,
   21.4,
   19.6,
   21.0,
   21.9,
   20.3,
   19.7,
   18.3,
   16.7,
   16.0,
   16.2,
   16.4,
   16.5,
   16.4,
   16.3,
   15.7,
   14.6,
   15.4,
   15.7,
   16.7,
   19.5,
   21.8,
   24.5,
   26.4,
   27.7,
   27.6,
   26.9,
   25.6,
   24.2,
   24.8,
   22.8,
   20.9,
   19.5,
   18.8,
   18.3,
   19.0,
   20.0,
   18.4,
   17.2,
   16.3,
   16.0,
   15.6,
   15.6,
   17.5,
   20.8,
   23.5,
   26.1,
   26.5,
   27.3,
   27.7,
   27.3,
   25.7,
   25.0,
   26.6,
   24.5,
   23.3,
   21.7,
   19.9,
   18.8,
   19.2,
   18.8,
   17.7,
   18.5,
   16.9,
   17.0,
   17.5,
   17.7,
   18.0,
   19.4,
   21.8,
   21.3,
   21.7,
   20.3,
   20.2,
   19.2,
   18.5,
   18.0,
   17.2,
   15.7,
   15.8,
   16.4,
   15.8,
   16.0,
   13.9],
  'wind_gusts_10m': [22.0,
   29.5,
   19.8,
   18.4,
   15.8,
   9.0,
   6.5,
   11.9,
   16.6,
   16.2,
   14.0,
   15.8,
   15.5,
   15.5,
   16.2,
   15.1,
   14.8,
   11.9,
   14.4,
   13.3,
   6.5,
   4.0,
   11.9,
   13.7,
   4.7,
   15.1,
   15.8,
   13.3,
   14.0,
   14.0,
   15.8,
   14.0,
   12.6,
   13.0,
   12.2,
   14.4,
   16.2,
   17.3,
   18.4,
   20.2,
   22.0,
   21.6,
   7.2,
   2.9,
   2.9,
   15.5,
   20.2,
   18.0,
   19.4,
   20.9,
   24.8,
   23.0,
   19.4,
   28.1,
   19.4,
   20.5,
   25.2,
   31.0,
   29.5,
   34.6,
   28.4,
   47.5,
   45.7,
   35.3,
   35.3,
   31.7,
   14.0,
   33.1,
   31.7,
   39.2,
   47.5,
   43.6,
   28.1,
   18.0,
   16.9,
   23.0,
   23.4,
   22.0,
   20.9,
   18.0,
   18.0,
   22.3,
   28.4,
   31.7,
   31.3,
   19.8,
   28.1,
   26.3,
   18.4,
   14.8,
   17.3,
   15.1,
   27.0,
   21.2,
   16.6,
   9.0,
   11.9,
   11.9,
   9.0,
   14.4,
   16.6,
   16.2,
   9.0,
   11.5,
   14.0,
   12.2,
   12.2,
   14.0,
   20.9,
   21.2,
   20.5,
   20.5,
   18.7,
   14.8,
   10.4,
   10.8,
   9.7,
   8.3,
   10.4,
   10.8,
   13.0,
   8.6,
   12.6,
   12.2,
   12.6,
   11.5,
   11.2,
   10.8,
   11.9,
   12.6,
   13.3,
   16.9,
   20.9,
   20.2,
   22.3,
   22.0,
   20.2,
   20.2,
   7.2,
   6.1,
   2.9,
   7.2,
   12.6,
   14.0,
   15.1,
   25.9,
   19.8,
   16.6,
   19.4,
   19.4,
   12.2,
   19.1,
   19.1,
   18.0,
   30.6,
   20.9,
   24.8,
   27.0,
   40.0,
   35.6,
   36.0,
   38.9,
   36.7,
   30.2,
   21.2,
   22.7,
   20.5,
   14.8],
  'vapour_pressure_deficit': [1.02,
   0.95,
   0.59,
   0.57,
   0.4,
   0.45,
   0.33,
   0.47,
   0.7,
   1.09,
   1.42,
   1.71,
   2.01,
   2.23,
   2.41,
   2.47,
   2.4,
   1.66,
   1.17,
   0.79,
   0.86,
   0.84,
   0.61,
   0.48,
   0.47,
   0.47,
   0.5,
   0.52,
   0.59,
   0.58,
   0.65,
   0.67,
   0.89,
   1.34,
   1.43,
   2.24,
   2.75,
   2.91,
   2.95,
   2.97,
   2.62,
   1.66,
   1.63,
   1.41,
   1.47,
   1.15,
   1.02,
   1.01,
   1.31,
   1.44,
   1.87,
   1.75,
   1.01,
   0.57,
   0.81,
   0.49,
   0.62,
   0.78,
   0.95,
   0.27,
   0.31,
   0.39,
   0.48,
   0.67,
   0.72,
   0.99,
   0.8,
   0.46,
   0.24,
   0.19,
   0.24,
   0.2,
   0.18,
   0.18,
   0.17,
   0.13,
   0.17,
   0.2,
   0.27,
   0.32,
   0.54,
   0.86,
   0.94,
   0.84,
   1.01,
   0.65,
   0.58,
   0.58,
   0.59,
   0.55,
   0.31,
   0.19,
   0.27,
   0.27,
   0.26,
   0.33,
   0.33,
   0.27,
   0.31,
   0.29,
   0.22,
   0.19,
   0.23,
   0.37,
   0.57,
   0.97,
   1.26,
   1.49,
   1.74,
   1.8,
   1.97,
   1.91,
   1.78,
   1.43,
   0.88,
   0.61,
   0.44,
   0.38,
   0.37,
   0.43,
   0.52,
   0.35,
   0.23,
   0.19,
   0.2,
   0.21,
   0.2,
   0.36,
   0.62,
   0.95,
   1.33,
   1.96,
   2.06,
   2.11,
   2.15,
   2.14,
   2.09,
   1.83,
   1.05,
   1.0,
   0.92,
   0.7,
   0.66,
   0.68,
   0.86,
   0.72,
   0.49,
   0.49,
   0.41,
   0.69,
   0.65,
   0.87,
   1.03,
   1.15,
   1.01,
   0.98,
   0.67,
   0.45,
   0.3,
   0.23,
   0.29,
   0.22,
   0.13,
   0.1,
   0.1,
   0.12,
   0.13,
   0.15],
  'relative_humidity_2m': [58,
   62,
   73,
   73,
   80,
   79,
   83,
   78,
   72,
   61,
   55,
   50,
   45,
   41,
   38,
   36,
   36,
   51,
   61,
   70,
   67,
   66,
   74,
   79,
   79,
   79,
   78,
   77,
   74,
   74,
   71,
   71,
   66,
   58,
   57,
   43,
   36,
   33,
   33,
   32,
   35,
   58,
   55,
   56,
   52,
   59,
   62,
   63,
   55,
   51,
   41,
   42,
   59,
   76,
   68,
   79,
   76,
   72,
   67,
   88,
   87,
   84,
   81,
   74,
   72,
   63,
   68,
   80,
   89,
   91,
   88,
   90,
   90,
   90,
   90,
   93,
   90,
   88,
   85,
   83,
   77,
   68,
   64,
   66,
   64,
   72,
   75,
   75,
   76,
   76,
   85,
   91,
   86,
   85,
   85,
   82,
   82,
   85,
   83,
   84,
   87,
   89,
   87,
   80,
   74,
   61,
   55,
   50,
   46,
   45,
   41,
   42,
   43,
   53,
   66,
   74,
   80,
   81,
   82,
   80,
   76,
   83,
   88,
   89,
   89,
   88,
   89,
   82,
   73,
   64,
   56,
   40,
   39,
   39,
   39,
   38,
   38,
   45,
   63,
   62,
   63,
   69,
   70,
   70,
   62,
   66,
   76,
   76,
   78,
   67,
   68,
   61,
   57,
   56,
   60,
   62,
   72,
   81,
   86,
   89,
   86,
   89,
   93,
   94,
   94,
   93,
   93,
   91]}}

In [117]:
weather = weather["hourly"]

In [118]:
weather_data = pd.DataFrame(weather)

In [119]:
weather_data.rename(columns={'time':'datetime'}, inplace=True)
weather_data

,datetime,wind_speed_100m,precipitation,apparent_temperature,wind_gusts_10m,vapour_pressure_deficit,relative_humidity_2m
0,2026-04-01T00:00,28.3,0.0,19.2,22.0,1.02,58
1,2026-04-01T01:00,24.0,0.0,20.6,29.5,0.95,62
2,2026-04-01T02:00,15.5,0.0,19.1,19.8,0.59,73
3,2026-04-01T03:00,20.3,0.0,18.4,18.4,0.57,73
4,2026-04-01T04:00,16.4,0.0,17.9,15.8,0.40,80
...,...,...,...,...,...,...,...
163,2026-04-07T19:00,21.2,3.2,15.8,30.2,0.10,94
164,2026-04-07T20:00,18.6,2.2,16.4,21.2,0.10,94
165,2026-04-07T21:00,21.3,0.7,15.8,22.7,0.12,93
166,2026-04-07T22:00,16.7,0.2,16.0,20.5,0.13,93
167,2026-04-07T23:00,28.0,0.1,13.9,14.8,0.15,91

In [120]:
weather_data['datetime'] = pd.to_datetime(weather_data['datetime'])
weather_data

,datetime,wind_speed_100m,precipitation,apparent_temperature,wind_gusts_10m,vapour_pressure_deficit,relative_humidity_2m
0,2026-04-01 00:00:00,28.3,0.0,19.2,22.0,1.02,58
1,2026-04-01 01:00:00,24.0,0.0,20.6,29.5,0.95,62
2,2026-04-01 02:00:00,15.5,0.0,19.1,19.8,0.59,73
3,2026-04-01 03:00:00,20.3,0.0,18.4,18.4,0.57,73
4,2026-04-01 04:00:00,16.4,0.0,17.9,15.8,0.40,80
...,...,...,...,...,...,...,...
163,2026-04-07 19:00:00,21.2,3.2,15.8,30.2,0.10,94
164,2026-04-07 20:00:00,18.6,2.2,16.4,21.2,0.10,94
165,2026-04-07 21:00:00,21.3,0.7,15.8,22.7,0.12,93
166,2026-04-07 22:00:00,16.7,0.2,16.0,20.5,0.13,93
167,2026-04-07 23:00:00,28.0,0.1,13.9,14.8,0.15,91

In [156]:
data

,aqi,co,no2,o3,so2,pm2_5,pm10,nh3,datetime,date,hour
0,4,1214.09,24.55,4.90,1.44,65.62,103.18,11.48,2026-04-01 00:00:00,2026-04-01,0
1,4,1221.59,22.94,3.32,1.67,67.00,105.27,15.45,2026-04-01 01:00:00,2026-04-01,1
2,4,1272.21,21.70,3.92,2.31,69.29,110.10,19.48,2026-04-01 02:00:00,2026-04-01,2
3,4,1339.46,19.50,12.07,3.33,73.07,116.39,23.76,2026-04-01 03:00:00,2026-04-01,3
4,4,1010.30,22.92,38.87,9.01,66.36,99.81,17.71,2026-04-01 04:00:00,2026-04-01,4
...,...,...,...,...,...,...,...,...,...,...,...
139,3,473.60,11.11,64.32,4.09,33.74,40.99,6.75,2026-04-07 19:00:00,2026-04-07,19
140,3,472.73,10.13,59.19,3.13,34.66,41.79,7.15,2026-04-07 20:00:00,2026-04-07,20
141,3,468.68,9.06,54.81,2.54,35.36,42.53,8.13,2026-04-07 21:00:00,2026-04-07,21
142,3,469.23,8.33,48.83,2.07,36.26,44.16,10.18,2026-04-07 22:00:00,2026-04-07,22
143,3,478.99,8.05,41.10,1.70,37.61,46.72,12.97,2026-04-07 23:00:00,2026-04-07,23

In [158]:
final_df = pd.merge(weather_data,data,"inner","datetime")

In [159]:
final_df

,datetime,wind_speed_100m,precipitation,apparent_temperature,wind_gusts_10m,vapour_pressure_deficit,relative_humidity_2m,aqi,co,no2,o3,so2,pm2_5,pm10,nh3,date,hour
0,2026-04-01 00:00:00,28.3,0.0,19.2,22.0,1.02,58,4,1214.09,24.55,4.90,1.44,65.62,103.18,11.48,2026-04-01,0
1,2026-04-01 01:00:00,24.0,0.0,20.6,29.5,0.95,62,4,1221.59,22.94,3.32,1.67,67.00,105.27,15.45,2026-04-01,1
2,2026-04-01 02:00:00,15.5,0.0,19.1,19.8,0.59,73,4,1272.21,21.70,3.92,2.31,69.29,110.10,19.48,2026-04-01,2
3,2026-04-01 03:00:00,20.3,0.0,18.4,18.4,0.57,73,4,1339.46,19.50,12.07,3.33,73.07,116.39,23.76,2026-04-01,3
4,2026-04-01 04:00:00,16.4,0.0,17.9,15.8,0.40,80,4,1010.30,22.92,38.87,9.01,66.36,99.81,17.71,2026-04-01,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2026-04-07 19:00:00,21.2,3.2,15.8,30.2,0.10,94,3,473.60,11.11,64.32,4.09,33.74,40.99,6.75,2026-04-07,19
140,2026-04-07 20:00:00,18.6,2.2,16.4,21.2,0.10,94,3,472.73,10.13,59.19,3.13,34.66,41.79,7.15,2026-04-07,20
141,2026-04-07 21:00:00,21.3,0.7,15.8,22.7,0.12,93,3,468.68,9.06,54.81,2.54,35.36,42.53,8.13,2026-04-07,21
142,2026-04-07 22:00:00,16.7,0.2,16.0,20.5,0.13,93,3,469.23,8.33,48.83,2.07,36.26,44.16,10.18,2026-04-07,22
143,2026-04-07 23:00:00,28.0,0.1,13.9,14.8,0.15,91,3,478.99,8.05,41.10,1.70,37.61,46.72,12.97,2026-04-07,23